/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rentalsystem.View;

import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        menubarPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        landlordsButton = new javax.swing.JButton();
        errorsButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        otherButton = new javax.swing.JButton();
        adminDashboard = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        landlordPanel = new javax.swing.JPanel();
        landlordFormPanel = new javax.swing.JPanel();
        landlordidDisplayLabel = new javax.swing.JLabel();
        landlordEmailDisplayLabel = new javax.swing.JLabel();
        landlordPhoneNumberDisplayLabel = new javax.swing.JLabel();
        landlordidTextField = new javax.swing.JTextField();
        landlordFirstnameTextField = new javax.swing.JTextField();
        landlordPhoneNumberTextField = new javax.swing.JTextField();
        landlordLastnameDisplayLabel = new javax.swing.JLabel();
        landlordLastnameTextField = new javax.swing.JTextField();
        landlordFirstnameDisplayLabel = new javax.swing.JLabel();
        landlordEmailTextField = new javax.swing.JTextField();
        landlordButtonPanel = new javax.swing.JPanel();
        landlordClearFormButton = new javax.swing.JButton();
        landlordAddButton = new javax.swing.JButton();
        landlordUpdateButton = new javax.swing.JButton();
        landlordDeleteButton = new javax.swing.JButton();
        landlordListScrollPane = new javax.swing.JScrollPane();
        landlordListTable = new javax.swing.JTable();
        errorPanel = new javax.swing.JPanel();
        errorNewDisplayLabel = new javax.swing.JLabel();
        errorDetailsPanel = new javax.swing.JPanel();
        errorDetailsDisplayLabel = new javax.swing.JLabel();
        errorDetailsLogidDisplayLabel = new javax.swing.JLabel();
        errorDetialsDateDisplayLabel = new javax.swing.JLabel();
        errorDescriptionDisplayLabel = new javax.swing.JLabel();
        errorDetailsLogidTextField = new javax.swing.JTextField();
        errorDetialsDateTextField = new javax.swing.JTextField();
        errorDescriptionScrollPane = new javax.swing.JScrollPane();
        errorDescriptionTextArea = new javax.swing.JTextArea();
        errorLandlordDisplayLabel = new javax.swing.JLabel();
        errorLandlordTextField = new javax.swing.JTextField();
        errorLandlordInfoButton = new javax.swing.JButton();
        errorUpdateStatusButton = new javax.swing.JButton();
        errorDetialsStatusDisplayLabel = new javax.swing.JLabel();
        errorDetailsStatusComboBox = new javax.swing.JComboBox<>();
        errorReviewListScrollPane = new javax.swing.JScrollPane();
        errorReviewListTable = new javax.swing.JTable();
        errorReviewDisplayLabel = new javax.swing.JLabel();
        errorNewListScrollPane = new javax.swing.JScrollPane();
        errorNewListTable = new javax.swing.JTable();
        previousErrorListScrollPane = new javax.swing.JScrollPane();
        previousErrorListTable = new javax.swing.JTable();
        previousErrorDisplayLabel = new javax.swing.JLabel();
        previousErrorSearchTextField = new javax.swing.JTextField();
        previousErrorSearchButton = new javax.swing.JButton();
        othersPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminPanel.setBackground(new java.awt.Color(255, 204, 204));

        titlePanel.setBackground(new java.awt.Color(255, 204, 204));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        titleLabel.setText("Company Name");

        accountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rentalsystem/images/account.png"))); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountLabel)
                .addGap(30, 30, 30))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(accountLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        menubarPanel.setBackground(new java.awt.Color(255, 204, 204));
        menubarPanel.setPreferredSize(new java.awt.Dimension(320, 100));

        dashboardButton.setBackground(new java.awt.Color(242, 242, 242));
        dashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(51, 51, 51));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(51, 51, 51)));
        dashboardButton.setFocusPainted(false);
        dashboardButton.setFocusable(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(200, 50));
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        landlordsButton.setBackground(new java.awt.Color(242, 242, 242));
        landlordsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        landlordsButton.setForeground(new java.awt.Color(51, 51, 51));
        landlordsButton.setText("Landlords");
        landlordsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(51, 51, 51)));
        landlordsButton.setFocusPainted(false);
        landlordsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        landlordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordsButtonActionPerformed(evt);
            }
        });

        errorsButton.setBackground(new java.awt.Color(242, 242, 242));
        errorsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorsButton.setForeground(new java.awt.Color(51, 51, 51));
        errorsButton.setText("Error Logs");
        errorsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(51, 51, 51)));
        errorsButton.setFocusPainted(false);
        errorsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        errorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorsButtonActionPerformed(evt);
            }
        });

        signoutButton.setBackground(new java.awt.Color(242, 242, 242));
        signoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(51, 51, 51));
        signoutButton.setText("Sign Out");
        signoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(51, 51, 51)));
        signoutButton.setFocusPainted(false);
        signoutButton.setPreferredSize(new java.awt.Dimension(200, 50));

        otherButton.setBackground(new java.awt.Color(242, 242, 242));
        otherButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        otherButton.setForeground(new java.awt.Color(51, 51, 51));
        otherButton.setText("Others");
        otherButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(51, 51, 51)));
        otherButton.setFocusPainted(false);
        otherButton.setPreferredSize(new java.awt.Dimension(200, 50));
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menubarPanelLayout = new javax.swing.GroupLayout(menubarPanel);
        menubarPanel.setLayout(menubarPanelLayout);
        menubarPanelLayout.setHorizontalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landlordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        menubarPanelLayout.setVerticalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(landlordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(errorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        adminDashboard.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );

        adminDashboard.add(homePanel, "card2");

        landlordidDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordidDisplayLabel.setText("Landlord ID");

        landlordEmailDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordEmailDisplayLabel.setText("Email");

        landlordPhoneNumberDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordPhoneNumberDisplayLabel.setText("Phone Number");

        landlordidTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordidTextFieldActionPerformed(evt);
            }
        });

        landlordFirstnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        landlordFirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordFirstnameTextFieldActionPerformed(evt);
            }
        });

        landlordPhoneNumberTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordPhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordPhoneNumberTextFieldActionPerformed(evt);
            }
        });

        landlordLastnameDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordLastnameDisplayLabel.setText("Last Name");

        landlordLastnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        landlordLastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordLastnameTextFieldActionPerformed(evt);
            }
        });

        landlordFirstnameDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        landlordFirstnameDisplayLabel.setText("First Name");

        landlordEmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        landlordEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordEmailTextFieldActionPerformed(evt);
            }
        });

        landlordClearFormButton.setBackground(new java.awt.Color(255, 255, 204));
        landlordClearFormButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        landlordClearFormButton.setText("CLEAR");
        landlordClearFormButton.setBorder(null);
        landlordClearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordClearFormButtonActionPerformed(evt);
            }
        });

        landlordAddButton.setBackground(new java.awt.Color(255, 255, 204));
        landlordAddButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        landlordAddButton.setText("ADD");
        landlordAddButton.setBorder(null);
        landlordAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordAddButtonActionPerformed(evt);
            }
        });

        landlordUpdateButton.setBackground(new java.awt.Color(255, 255, 204));
        landlordUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        landlordUpdateButton.setText("UPDATE");
        landlordUpdateButton.setBorder(null);
        landlordUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordUpdateButtonActionPerformed(evt);
            }
        });

        landlordDeleteButton.setBackground(new java.awt.Color(255, 255, 204));
        landlordDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        landlordDeleteButton.setText("DELETE");
        landlordDeleteButton.setBorder(null);
        landlordDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout landlordButtonPanelLayout = new javax.swing.GroupLayout(landlordButtonPanel);
        landlordButtonPanel.setLayout(landlordButtonPanelLayout);
        landlordButtonPanelLayout.setHorizontalGroup(
            landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordButtonPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landlordAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(landlordUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landlordDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(landlordClearFormButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        landlordButtonPanelLayout.setVerticalGroup(
            landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landlordClearFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landlordAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(landlordButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landlordUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landlordDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout landlordFormPanelLayout = new javax.swing.GroupLayout(landlordFormPanel);
        landlordFormPanel.setLayout(landlordFormPanelLayout);
        landlordFormPanelLayout.setHorizontalGroup(
            landlordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordFormPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(landlordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landlordFirstnameDisplayLabel)
                    .addComponent(landlordLastnameDisplayLabel)
                    .addComponent(landlordidDisplayLabel)
                    .addComponent(landlordPhoneNumberDisplayLabel)
                    .addComponent(landlordEmailDisplayLabel)
                    .addComponent(landlordButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(landlordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(landlordidTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(landlordFirstnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(landlordLastnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(landlordPhoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(landlordEmailTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        landlordFormPanelLayout.setVerticalGroup(
            landlordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordFormPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(landlordidDisplayLabel)
                .addGap(8, 8, 8)
                .addComponent(landlordidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(landlordFirstnameDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordFirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(landlordLastnameDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordLastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(landlordEmailDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(landlordPhoneNumberDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(landlordButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        landlordListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "No. of properties", "No. of tenants"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        landlordListScrollPane.setViewportView(landlordListTable);

        javax.swing.GroupLayout landlordPanelLayout = new javax.swing.GroupLayout(landlordPanel);
        landlordPanel.setLayout(landlordPanelLayout);
        landlordPanelLayout.setHorizontalGroup(
            landlordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landlordPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(landlordFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        landlordPanelLayout.setVerticalGroup(
            landlordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landlordFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(landlordListScrollPane)
        );

        adminDashboard.add(landlordPanel, "card2");

        errorNewDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        errorNewDisplayLabel.setText("New Errors");

        errorDetailsDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        errorDetailsDisplayLabel.setText("Details");

        errorDetailsLogidDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorDetailsLogidDisplayLabel.setText("Log ID");

        errorDetialsDateDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorDetialsDateDisplayLabel.setText("Date Issued");

        errorDescriptionDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorDescriptionDisplayLabel.setText("Description");

        errorDetailsLogidTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        errorDetailsLogidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorDetailsLogidTextFieldActionPerformed(evt);
            }
        });

        errorDetialsDateTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        errorDetialsDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorDetialsDateTextFieldActionPerformed(evt);
            }
        });

        errorDescriptionScrollPane.setPreferredSize(new java.awt.Dimension(200, 90));

        errorDescriptionTextArea.setColumns(20);
        errorDescriptionTextArea.setRows(5);
        errorDescriptionScrollPane.setViewportView(errorDescriptionTextArea);

        errorLandlordDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorLandlordDisplayLabel.setText("Landlord");

        errorLandlordTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        errorLandlordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorLandlordTextFieldActionPerformed(evt);
            }
        });

        errorLandlordInfoButton.setBackground(new java.awt.Color(239, 255, 255));
        errorLandlordInfoButton.setText("More Info");
        errorLandlordInfoButton.setPreferredSize(new java.awt.Dimension(150, 30));
        errorLandlordInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorLandlordInfoButtonActionPerformed(evt);
            }
        });

        errorUpdateStatusButton.setBackground(new java.awt.Color(239, 255, 255));
        errorUpdateStatusButton.setText("Update Status");
        errorUpdateStatusButton.setPreferredSize(new java.awt.Dimension(150, 30));
        errorUpdateStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorUpdateStatusButtonActionPerformed(evt);
            }
        });

        errorDetialsStatusDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorDetialsStatusDisplayLabel.setText("Status");

        errorDetailsStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Send", "Received", "In Review", "Rectified" }));
        errorDetailsStatusComboBox.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout errorDetailsPanelLayout = new javax.swing.GroupLayout(errorDetailsPanel);
        errorDetailsPanel.setLayout(errorDetailsPanelLayout);
        errorDetailsPanelLayout.setHorizontalGroup(
            errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDetailsPanelLayout.createSequentialGroup()
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errorDescriptionDisplayLabel)
                            .addComponent(errorDetialsDateDisplayLabel)
                            .addComponent(errorDetailsLogidDisplayLabel)
                            .addComponent(errorLandlordDisplayLabel)
                            .addComponent(errorDetialsStatusDisplayLabel))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorDetailsDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(errorDetailsStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorUpdateStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(errorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(errorLandlordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorLandlordInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorDetailsLogidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorDetialsDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, Short.MAX_VALUE))
        );
        errorDetailsPanelLayout.setVerticalGroup(
            errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDetailsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(errorDetailsDisplayLabel)
                .addGap(18, 18, 18)
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorDetailsLogidDisplayLabel)
                    .addComponent(errorDetailsLogidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorDetialsDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorDetialsDateDisplayLabel))
                .addGap(17, 17, 17)
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorDetialsStatusDisplayLabel)
                    .addComponent(errorUpdateStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorDetailsStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorLandlordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorLandlordDisplayLabel)
                    .addComponent(errorLandlordInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(errorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDescriptionDisplayLabel)
                    .addComponent(errorDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        errorReviewListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Log ID", "Landlord Name", "Date Issued"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        errorReviewListScrollPane.setViewportView(errorReviewListTable);

        errorReviewDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        errorReviewDisplayLabel.setText("Error logs in Review");

        errorNewListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Log ID", "Landlord Name", "Date Issued"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        errorNewListScrollPane.setViewportView(errorNewListTable);

        previousErrorListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "LandLordName", "Date Issued"
            }
        ));
        previousErrorListScrollPane.setViewportView(previousErrorListTable);

        previousErrorDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        previousErrorDisplayLabel.setText("Previous");

        previousErrorSearchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        previousErrorSearchTextField.setText("Search");
        previousErrorSearchTextField.setPreferredSize(new java.awt.Dimension(200, 40));

        previousErrorSearchButton.setBackground(new java.awt.Color(248, 255, 255));
        previousErrorSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        previousErrorSearchButton.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documents\\UoN-notes\\YEAR 2\\CSY2094 - JAVA\\1 AS2\\RentalSystem\\src\\main\\java\\com\\mycompany\\rentalsystem\\images\\magnifying-glass.png")); // NOI18N
        previousErrorSearchButton.setBorder(null);

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(errorNewListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(errorPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(previousErrorDisplayLabel)
                                    .addGroup(errorPanelLayout.createSequentialGroup()
                                        .addComponent(previousErrorSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(previousErrorSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(errorPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(previousErrorListScrollPane))))
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(errorNewDisplayLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(errorPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(errorReviewListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(errorPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(errorReviewDisplayLabel)))
                        .addGap(18, 18, 18)
                        .addComponent(errorDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorNewDisplayLabel)
                    .addComponent(previousErrorDisplayLabel))
                .addGap(18, 18, 18)
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previousErrorSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previousErrorSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previousErrorListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(errorNewListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(errorReviewDisplayLabel)
                        .addGap(8, 8, 8)
                        .addComponent(errorReviewListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminDashboard.add(errorPanel, "card3");

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );

        adminDashboard.add(othersPanel, "card2");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(menubarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDashboard))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menubarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                    .addComponent(adminDashboard)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        adminDashboard.removeAll();
        adminDashboard.add(homePanel);
        adminDashboard.repaint();
        adminDashboard.revalidate();

    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void landlordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordsButtonActionPerformed
        // TODO add your handling code here:
        adminDashboard.removeAll();
        adminDashboard.add(landlordPanel);
        adminDashboard.repaint();
        adminDashboard.revalidate();
    }//GEN-LAST:event_landlordsButtonActionPerformed

    private void errorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorsButtonActionPerformed
        // TODO add your handling code here:
        adminDashboard.removeAll();
        adminDashboard.add(errorPanel);
        adminDashboard.repaint();
        adminDashboard.revalidate();
    }//GEN-LAST:event_errorsButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        // TODO add your handling code here:
        adminDashboard.removeAll();
        adminDashboard.add(othersPanel);
        adminDashboard.repaint();
        adminDashboard.revalidate();
    }//GEN-LAST:event_otherButtonActionPerformed

    private void landlordidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordidTextFieldActionPerformed

    private void landlordFirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordFirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordFirstnameTextFieldActionPerformed

    private void landlordPhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordPhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordPhoneNumberTextFieldActionPerformed

    private void landlordLastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordLastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordLastnameTextFieldActionPerformed

    private void landlordEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordEmailTextFieldActionPerformed

    private void landlordClearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordClearFormButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_landlordClearFormButtonActionPerformed

    private void landlordAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordAddButtonActionPerformed

    private void landlordUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordUpdateButtonActionPerformed

    private void landlordDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordDeleteButtonActionPerformed

    private void errorDetailsLogidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorDetailsLogidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorDetailsLogidTextFieldActionPerformed

    private void errorDetialsDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorDetialsDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorDetialsDateTextFieldActionPerformed

    private void errorLandlordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorLandlordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLandlordTextFieldActionPerformed

    private void errorLandlordInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorLandlordInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLandlordInfoButtonActionPerformed

    private void errorUpdateStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorUpdateStatusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorUpdateStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLayeredPane adminDashboard;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel errorDescriptionDisplayLabel;
    private javax.swing.JScrollPane errorDescriptionScrollPane;
    private javax.swing.JTextArea errorDescriptionTextArea;
    private javax.swing.JLabel errorDetailsDisplayLabel;
    private javax.swing.JLabel errorDetailsLogidDisplayLabel;
    private javax.swing.JTextField errorDetailsLogidTextField;
    private javax.swing.JPanel errorDetailsPanel;
    private javax.swing.JComboBox<String> errorDetailsStatusComboBox;
    private javax.swing.JLabel errorDetialsDateDisplayLabel;
    private javax.swing.JTextField errorDetialsDateTextField;
    private javax.swing.JLabel errorDetialsStatusDisplayLabel;
    private javax.swing.JLabel errorLandlordDisplayLabel;
    private javax.swing.JButton errorLandlordInfoButton;
    private javax.swing.JTextField errorLandlordTextField;
    private javax.swing.JLabel errorNewDisplayLabel;
    private javax.swing.JScrollPane errorNewListScrollPane;
    private javax.swing.JTable errorNewListTable;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel errorReviewDisplayLabel;
    private javax.swing.JScrollPane errorReviewListScrollPane;
    private javax.swing.JTable errorReviewListTable;
    private javax.swing.JButton errorUpdateStatusButton;
    private javax.swing.JButton errorsButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton landlordAddButton;
    private javax.swing.JPanel landlordButtonPanel;
    private javax.swing.JButton landlordClearFormButton;
    private javax.swing.JButton landlordDeleteButton;
    private javax.swing.JLabel landlordEmailDisplayLabel;
    private javax.swing.JTextField landlordEmailTextField;
    private javax.swing.JLabel landlordFirstnameDisplayLabel;
    private javax.swing.JTextField landlordFirstnameTextField;
    private javax.swing.JPanel landlordFormPanel;
    private javax.swing.JLabel landlordLastnameDisplayLabel;
    private javax.swing.JTextField landlordLastnameTextField;
    private javax.swing.JScrollPane landlordListScrollPane;
    private javax.swing.JTable landlordListTable;
    private javax.swing.JPanel landlordPanel;
    private javax.swing.JLabel landlordPhoneNumberDisplayLabel;
    private javax.swing.JTextField landlordPhoneNumberTextField;
    private javax.swing.JButton landlordUpdateButton;
    private javax.swing.JLabel landlordidDisplayLabel;
    private javax.swing.JTextField landlordidTextField;
    private javax.swing.JButton landlordsButton;
    private javax.swing.JPanel menubarPanel;
    private javax.swing.JButton otherButton;
    private javax.swing.JPanel othersPanel;
    private javax.swing.JLabel previousErrorDisplayLabel;
    private javax.swing.JScrollPane previousErrorListScrollPane;
    private javax.swing.JTable previousErrorListTable;
    private javax.swing.JButton previousErrorSearchButton;
    private javax.swing.JTextField previousErrorSearchTextField;
    private javax.swing.JButton signoutButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
