/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rentalsystem.View;

import java.awt.event.ActionListener;
import javax.swing.JFrame;


/**
 *
 * @author HP
 */
public class TenantView extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TenantView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void addDashboardButtonListener(ActionListener menubarListener){
        dashboardButton.addActionListener(menubarListener);
    }

    public void addPaymentButtonListener(ActionListener menubarListener) {
        paymentButton.addActionListener(menubarListener);
    }

    public void addMaintenanceButtonListener(ActionListener menubarListener) {
        maintenanceButton.addActionListener(menubarListener);
    }

    public void addOtherButtonListener(ActionListener menubarListener) {
        otherButton.addActionListener(menubarListener);
    }

    public void addSignoutButtonListener(ActionListener menubarListener) {
        signoutButton.addActionListener(menubarListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenantDashboard1 = new javax.swing.JTabbedPane();
        tenantPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        menubarScrollPane = new javax.swing.JScrollPane();
        menubarPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        otherButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        tenantDashboard = new javax.swing.JLayeredPane();
        dashboardPanel = new javax.swing.JPanel();
        greetingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tenantName = new javax.swing.JLabel();
        paymentDetailPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        displayRentLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        displayDateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homePaymentButton = new javax.swing.JButton();
        receiptPanel = new javax.swing.JPanel();
        maintenanceTrackingPanel = new javax.swing.JPanel();
        dashboardMaintenanceSummaryScrollPane = new javax.swing.JScrollPane();
        dashboardMaintenanceSummaryTable = new javax.swing.JTable();
        dashboardNewMaintenanceButton = new javax.swing.JButton();
        notificationPanel = new javax.swing.JPanel();
        inspectionScrollPane = new javax.swing.JScrollPane();
        inspectionTable = new javax.swing.JTable();
        paymentPanel = new javax.swing.JPanel();
        costDetailsPanel = new javax.swing.JPanel();
        costBreakdownPanel = new javax.swing.JPanel();
        amountToPayDisplayLabel = new javax.swing.JLabel();
        breakdownRentDisplayLabel = new javax.swing.JLabel();
        breakdownDamagesDisplayLabel = new javax.swing.JLabel();
        breakdownLateDisplayLabel = new javax.swing.JLabel();
        breakdownRentAmountLabel = new javax.swing.JLabel();
        breakdownDamagesAmountLabel = new javax.swing.JLabel();
        breakdownLateAmountLabel = new javax.swing.JLabel();
        breakdownTotalAmountDisplayLabel = new javax.swing.JLabel();
        breakdownTotalAmountLabel = new javax.swing.JLabel();
        dueDateDisplayLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        costActionsPanel = new javax.swing.JPanel();
        actionPayDisplayLabel = new javax.swing.JLabel();
        actionPayStripeButton = new javax.swing.JButton();
        actionPayPaypalButton = new javax.swing.JButton();
        actionPayVisaButton = new javax.swing.JButton();
        paymentHistoryListScrollPane = new javax.swing.JScrollPane();
        paymentHistoryListTable = new javax.swing.JTable();
        maintenancePanel = new javax.swing.JPanel();
        maintenanceRequestPanel = new javax.swing.JPanel();
        maintenanceRequestSearchTextField = new javax.swing.JTextField();
        maintenanceRequestSearchButton = new javax.swing.JButton();
        maintenanceRequestListScrollPane = new javax.swing.JScrollPane();
        maintenanceRequestListTable = new javax.swing.JTable();
        maintenanceDetailsPanel = new javax.swing.JPanel();
        maintenanceDescriptionLabel = new javax.swing.JLabel();
        maintenanceDescriptionScrollPane = new javax.swing.JScrollPane();
        maintenanceDescriptionTextArea = new javax.swing.JTextArea();
        maintenanceRequestSubmitButton = new javax.swing.JButton();
        othersPanel = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        tenantFormPanel = new javax.swing.JPanel();
        tenantidDisplayLabel = new javax.swing.JLabel();
        genderDisplayLabel = new javax.swing.JLabel();
        emailDisplayLabel = new javax.swing.JLabel();
        phoneNumberDisplayLabel = new javax.swing.JLabel();
        lastnameDisplayLabel = new javax.swing.JLabel();
        firstnameDisplayLabel = new javax.swing.JLabel();
        dobDisplayLabel = new javax.swing.JLabel();
        tenantidValueLabel = new javax.swing.JLabel();
        tenantFirstnameValueLabel = new javax.swing.JLabel();
        tenantGenderValueLabel1 = new javax.swing.JLabel();
        tenantEmailValueLabel = new javax.swing.JLabel();
        tenantLastnameValueLabel1 = new javax.swing.JLabel();
        tenantPhoneValueLabel = new javax.swing.JLabel();
        tenantDobValueLabel = new javax.swing.JLabel();
        tenantDobValueLabel1 = new javax.swing.JLabel();

        tenantDashboard1.setBackground(new java.awt.Color(255, 204, 204));
        tenantDashboard1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tenantDashboard1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tenantDashboard1.setEnabled(false);
        tenantDashboard1.setFocusable(false);
        tenantDashboard1.setRequestFocusEnabled(false);
        tenantDashboard1.setVerifyInputWhenFocusTarget(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        tenantPanel.setBackground(new java.awt.Color(255, 204, 204));

        titlePanel.setBackground(new java.awt.Color(255, 204, 204));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        titleLabel.setText("Company Name");

        accountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rentalsystem/images/account.png"))); // NOI18N
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1223, Short.MAX_VALUE)
                .addComponent(accountLabel)
                .addGap(30, 30, 30))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(accountLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        menubarScrollPane.setBorder(null);

        menubarPanel.setBackground(new java.awt.Color(255, 204, 204));
        menubarPanel.setPreferredSize(new java.awt.Dimension(320, 100));

        dashboardButton.setBackground(new java.awt.Color(51, 51, 51));
        dashboardButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(204, 204, 204));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        dashboardButton.setFocusPainted(false);
        dashboardButton.setFocusable(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(200, 50));
        

        paymentButton.setBackground(new java.awt.Color(51, 51, 51));
        paymentButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(204, 204, 204));
        paymentButton.setText("Payment");
        paymentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        paymentButton.setFocusPainted(false);
        paymentButton.setPreferredSize(new java.awt.Dimension(200, 50));
        

        maintenanceButton.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maintenanceButton.setForeground(new java.awt.Color(204, 204, 204));
        maintenanceButton.setText("Maintenance");
        maintenanceButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        maintenanceButton.setFocusPainted(false);
        maintenanceButton.setPreferredSize(new java.awt.Dimension(200, 50));
        

        otherButton.setBackground(new java.awt.Color(51, 51, 51));
        otherButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        otherButton.setForeground(new java.awt.Color(204, 204, 204));
        otherButton.setText("Others");
        otherButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        otherButton.setFocusPainted(false);
        otherButton.setPreferredSize(new java.awt.Dimension(200, 50));
        

        signoutButton.setBackground(new java.awt.Color(51, 51, 51));
        signoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(204, 204, 204));
        signoutButton.setText("Sign Out");
        signoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        signoutButton.setFocusPainted(false);
        signoutButton.setPreferredSize(new java.awt.Dimension(200, 50));
        
        javax.swing.GroupLayout menubarPanelLayout = new javax.swing.GroupLayout(menubarPanel);
        menubarPanel.setLayout(menubarPanelLayout);
        menubarPanelLayout.setHorizontalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        menubarPanelLayout.setVerticalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        menubarScrollPane.setViewportView(menubarPanel);

        tenantDashboard.setLayout(new java.awt.CardLayout());

        dashboardPanel.setBackground(new java.awt.Color(255, 204, 204));

        greetingPanel.setBackground(new java.awt.Color(255, 204, 204));
        greetingPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 153, 153)));
        greetingPanel.setPreferredSize(new java.awt.Dimension(286, 120));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        jLabel1.setText("Hi");

        tenantName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        tenantName.setText("Name");

        javax.swing.GroupLayout greetingPanelLayout = new javax.swing.GroupLayout(greetingPanel);
        greetingPanel.setLayout(greetingPanelLayout);
        greetingPanelLayout.setHorizontalGroup(
            greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greetingPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tenantName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        greetingPanelLayout.setVerticalGroup(
            greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greetingPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tenantName))
                .addGap(30, 30, 30))
        );

        paymentDetailPanel.setPreferredSize(new java.awt.Dimension(400, 275));

        jPanel1.setBackground(new java.awt.Color(255, 227, 227));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Next Payment of");

        displayRentLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        displayRentLabel.setForeground(new java.awt.Color(255, 102, 102));
        displayRentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayRentLabel.setText("999");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("due in ");

        displayDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        displayDateLabel.setForeground(new java.awt.Color(255, 102, 102));
        displayDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayDateLabel.setText("DD-MM-YYYY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayRentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayRentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayDateLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        homePaymentButton.setBackground(new java.awt.Color(255, 227, 227));
        homePaymentButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homePaymentButton.setForeground(new java.awt.Color(255, 51, 51));
        homePaymentButton.setText("PAY NOW");
        homePaymentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        




        javax.swing.GroupLayout paymentDetailPanelLayout = new javax.swing.GroupLayout(paymentDetailPanel);
        paymentDetailPanel.setLayout(paymentDetailPanelLayout);
        paymentDetailPanelLayout.setHorizontalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homePaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paymentDetailPanelLayout.setVerticalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        receiptPanel.setPreferredSize(new java.awt.Dimension(400, 275));

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        maintenanceTrackingPanel.setBackground(new java.awt.Color(255, 204, 204));
        maintenanceTrackingPanel.setPreferredSize(new java.awt.Dimension(400, 600));

        dashboardMaintenanceSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "Recieved", "arun"}
            },
            new String [] {
                "Ticket no", "Status", "Requested by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dashboardMaintenanceSummaryScrollPane.setViewportView(dashboardMaintenanceSummaryTable);

        dashboardNewMaintenanceButton.setBackground(new java.awt.Color(255, 227, 227));
        dashboardNewMaintenanceButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboardNewMaintenanceButton.setForeground(new java.awt.Color(255, 51, 51));
        dashboardNewMaintenanceButton.setText("New Request");
        dashboardNewMaintenanceButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        

        javax.swing.GroupLayout maintenanceTrackingPanelLayout = new javax.swing.GroupLayout(maintenanceTrackingPanel);
        maintenanceTrackingPanel.setLayout(maintenanceTrackingPanelLayout);
        maintenanceTrackingPanelLayout.setHorizontalGroup(
            maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTrackingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardMaintenanceSummaryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(dashboardNewMaintenanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceTrackingPanelLayout.setVerticalGroup(
            maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTrackingPanelLayout.createSequentialGroup()
                .addComponent(dashboardMaintenanceSummaryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardNewMaintenanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        notificationPanel.setPreferredSize(new java.awt.Dimension(0, 275));

        inspectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Inspector", "Status"
            }
        ));
        inspectionScrollPane.setViewportView(inspectionTable);

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationPanelLayout.createSequentialGroup()
                .addComponent(inspectionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inspectionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addComponent(paymentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(notificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addComponent(maintenanceTrackingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maintenanceTrackingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(notificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );

        tenantDashboard.add(dashboardPanel, "card2");

        paymentPanel.setPreferredSize(new java.awt.Dimension(1380, 810));

        amountToPayDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        amountToPayDisplayLabel.setText("Amount to Pay");

        breakdownRentDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        breakdownRentDisplayLabel.setText("Rent");

        breakdownDamagesDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        breakdownDamagesDisplayLabel.setText("Damages");

        breakdownLateDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        breakdownLateDisplayLabel.setText("Late Fee");

        breakdownRentAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        breakdownRentAmountLabel.setText("99");

        breakdownDamagesAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        breakdownDamagesAmountLabel.setText("99");

        breakdownLateAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        breakdownLateAmountLabel.setText("99");

        breakdownTotalAmountDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        breakdownTotalAmountDisplayLabel.setText("Total To pay");

        breakdownTotalAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        breakdownTotalAmountLabel.setText("999");

        dueDateDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dueDateDisplayLabel.setText("Due on: ");

        dueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dueDateLabel.setText("dd/mm/yyyy");

        javax.swing.GroupLayout costBreakdownPanelLayout = new javax.swing.GroupLayout(costBreakdownPanel);
        costBreakdownPanel.setLayout(costBreakdownPanelLayout);
        costBreakdownPanelLayout.setHorizontalGroup(
            costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, costBreakdownPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breakdownRentDisplayLabel))
                    .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(breakdownLateDisplayLabel)
                            .addComponent(breakdownDamagesDisplayLabel)
                            .addComponent(breakdownTotalAmountDisplayLabel))))
                .addGap(37, 37, 37)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breakdownRentAmountLabel)
                    .addComponent(breakdownDamagesAmountLabel)
                    .addComponent(breakdownLateAmountLabel)
                    .addComponent(breakdownTotalAmountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, costBreakdownPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(amountToPayDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(dueDateDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dueDateLabel)
                .addGap(30, 30, 30))
        );
        costBreakdownPanelLayout.setVerticalGroup(
            costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountToPayDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakdownRentDisplayLabel)
                    .addComponent(breakdownRentAmountLabel))
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakdownDamagesDisplayLabel)
                    .addComponent(breakdownDamagesAmountLabel))
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakdownLateDisplayLabel)
                    .addComponent(breakdownLateAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 51, Short.MAX_VALUE)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakdownTotalAmountDisplayLabel)
                    .addComponent(breakdownTotalAmountLabel))
                .addGap(40, 40, 40))
        );

        actionPayDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        actionPayDisplayLabel.setText("Pay Here");

        actionPayStripeButton.setBackground(new java.awt.Color(248, 255, 255));
        actionPayStripeButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        actionPayStripeButton.setText("Stripe");
        actionPayStripeButton.setPreferredSize(new java.awt.Dimension(250, 50));
        actionPayStripeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPayStripeButtonActionPerformed(evt);
            }
        });

        actionPayPaypalButton.setBackground(new java.awt.Color(248, 255, 255));
        actionPayPaypalButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        actionPayPaypalButton.setText("PayPal");
        actionPayPaypalButton.setPreferredSize(new java.awt.Dimension(250, 50));

        actionPayVisaButton.setBackground(new java.awt.Color(248, 255, 255));
        actionPayVisaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        actionPayVisaButton.setText("Visa");
        actionPayVisaButton.setPreferredSize(new java.awt.Dimension(250, 50));

        javax.swing.GroupLayout costActionsPanelLayout = new javax.swing.GroupLayout(costActionsPanel);
        costActionsPanel.setLayout(costActionsPanelLayout);
        costActionsPanelLayout.setHorizontalGroup(
            costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(actionPayDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionPayVisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPayStripeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPayPaypalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        costActionsPanelLayout.setVerticalGroup(
            costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(actionPayDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionPayStripeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(actionPayPaypalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(actionPayVisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        paymentHistoryListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "",  null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Due Date", "Paid on", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentHistoryListTable.getTableHeader().setReorderingAllowed(false);
        paymentHistoryListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentHistoryListTableMouseClicked(evt);
            }
        });
        paymentHistoryListScrollPane.setViewportView(paymentHistoryListTable);

        javax.swing.GroupLayout costDetailsPanelLayout = new javax.swing.GroupLayout(costDetailsPanel);
        costDetailsPanel.setLayout(costDetailsPanelLayout);
        costDetailsPanelLayout.setHorizontalGroup(
            costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(costDetailsPanelLayout.createSequentialGroup()
                        .addComponent(costBreakdownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paymentHistoryListScrollPane))
                .addContainerGap())
        );
        costDetailsPanelLayout.setVerticalGroup(
            costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costBreakdownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentHistoryListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(costDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tenantDashboard.add(paymentPanel, "card3");

        maintenancePanel.setPreferredSize(new java.awt.Dimension(1380, 810));

        maintenanceRequestSearchTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        maintenanceRequestSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceRequestSearchTextFieldActionPerformed(evt);
            }
        });

        maintenanceRequestSearchButton.setBackground(new java.awt.Color(248, 255, 255));
        maintenanceRequestSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maintenanceRequestSearchButton.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documents\\UoN-notes\\YEAR 2\\CSY2094 - JAVA\\1 AS2\\RentalSystem\\src\\main\\java\\com\\mycompany\\rentalsystem\\images\\magnifying-glass.png")); // NOI18N
        maintenanceRequestSearchButton.setBorder(null);

        maintenanceRequestListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maintenanceRequestListScrollPane.setViewportView(maintenanceRequestListTable);

        javax.swing.GroupLayout maintenanceRequestPanelLayout = new javax.swing.GroupLayout(maintenanceRequestPanel);
        maintenanceRequestPanel.setLayout(maintenanceRequestPanelLayout);
        maintenanceRequestPanelLayout.setHorizontalGroup(
            maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                .addGroup(maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(maintenanceRequestSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(maintenanceRequestSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(maintenanceRequestListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceRequestPanelLayout.setVerticalGroup(
            maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceRequestPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maintenanceRequestSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(maintenanceRequestSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintenanceRequestListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        maintenanceDescriptionLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        maintenanceDescriptionLabel.setText("Description");

        maintenanceDescriptionTextArea.setColumns(20);
        maintenanceDescriptionTextArea.setRows(5);
        maintenanceDescriptionScrollPane.setViewportView(maintenanceDescriptionTextArea);

        maintenanceRequestSubmitButton.setBackground(new java.awt.Color(248, 255, 255));
        maintenanceRequestSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maintenanceRequestSubmitButton.setText("Submit New Request");
        maintenanceRequestSubmitButton.setPreferredSize(new java.awt.Dimension(200, 50));
        maintenanceRequestSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceRequestSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maintenanceDetailsPanelLayout = new javax.swing.GroupLayout(maintenanceDetailsPanel);
        maintenanceDetailsPanel.setLayout(maintenanceDetailsPanelLayout);
        maintenanceDetailsPanelLayout.setHorizontalGroup(
            maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceDetailsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceDescriptionLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maintenanceRequestSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceDetailsPanelLayout.setVerticalGroup(
            maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maintenanceDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(maintenanceRequestSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout maintenancePanelLayout = new javax.swing.GroupLayout(maintenancePanel);
        maintenancePanel.setLayout(maintenancePanelLayout);
        maintenancePanelLayout.setHorizontalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        maintenancePanelLayout.setVerticalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maintenanceDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tenantDashboard.add(maintenancePanel, "card4");

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1376, Short.MAX_VALUE)
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );

        tenantDashboard.add(othersPanel, "card5");

        tenantidDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantidDisplayLabel.setText("Tenant ID");

        genderDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        genderDisplayLabel.setText("Gender");

        emailDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        emailDisplayLabel.setText("Email");

        phoneNumberDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        phoneNumberDisplayLabel.setText("Phone Number");

        lastnameDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lastnameDisplayLabel.setText("Last Name");

        firstnameDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        firstnameDisplayLabel.setText("First Name");

        dobDisplayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        dobDisplayLabel.setText("Date of Birth");

        tenantidValueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantidValueLabel.setText("1234");

        tenantFirstnameValueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantFirstnameValueLabel.setText("Male");

        tenantGenderValueLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantGenderValueLabel1.setText("Male");

        tenantEmailValueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantEmailValueLabel.setText("Male");

        tenantLastnameValueLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantLastnameValueLabel1.setText("Male");

        tenantPhoneValueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantPhoneValueLabel.setText("Male");

        tenantDobValueLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tenantDobValueLabel.setText("Male");

        tenantDobValueLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        tenantDobValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenantDobValueLabel1.setText("Your Info");

        javax.swing.GroupLayout tenantFormPanelLayout = new javax.swing.GroupLayout(tenantFormPanel);
        tenantFormPanel.setLayout(tenantFormPanelLayout);
        tenantFormPanelLayout.setHorizontalGroup(
            tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantFormPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnameDisplayLabel)
                    .addComponent(lastnameDisplayLabel)
                    .addComponent(dobDisplayLabel)
                    .addComponent(emailDisplayLabel)
                    .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tenantGenderValueLabel1)
                        .addGroup(tenantFormPanelLayout.createSequentialGroup()
                            .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tenantidDisplayLabel)
                                .addComponent(genderDisplayLabel))
                            .addGap(81, 81, 81)
                            .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tenantFirstnameValueLabel)
                                .addComponent(tenantidValueLabel)
                                .addComponent(tenantEmailValueLabel)
                                .addComponent(tenantLastnameValueLabel1)
                                .addComponent(tenantPhoneValueLabel)
                                .addComponent(tenantDobValueLabel))))
                    .addComponent(phoneNumberDisplayLabel))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(tenantFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenantDobValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tenantFormPanelLayout.setVerticalGroup(
            tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantFormPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(tenantDobValueLabel1)
                .addGap(50, 50, 50)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantidDisplayLabel)
                    .addComponent(tenantidValueLabel))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderDisplayLabel)
                    .addComponent(tenantGenderValueLabel1))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameDisplayLabel)
                    .addComponent(tenantFirstnameValueLabel))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameDisplayLabel)
                    .addComponent(tenantLastnameValueLabel1))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailDisplayLabel)
                    .addComponent(tenantEmailValueLabel))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberDisplayLabel)
                    .addComponent(tenantPhoneValueLabel))
                .addGap(18, 18, 18)
                .addGroup(tenantFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobDisplayLabel)
                    .addComponent(tenantDobValueLabel))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenantFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(854, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenantFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tenantDashboard.add(accountPanel, "card6");

        javax.swing.GroupLayout tenantPanelLayout = new javax.swing.GroupLayout(tenantPanel);
        tenantPanel.setLayout(tenantPanelLayout);
        tenantPanelLayout.setHorizontalGroup(
            tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tenantPanelLayout.createSequentialGroup()
                        .addComponent(menubarScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tenantPanelLayout.setVerticalGroup(
            tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenantDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menubarScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tenantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tenantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(dashboardPanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();

    }//GEN-LAST:event_dashboardButtonActionPerformed

    public void homePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePaymentButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(paymentPanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
    }//GEN-LAST:event_homePaymentButtonActionPerformed

    public void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(paymentPanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
    }//GEN-LAST:event_paymentButtonActionPerformed

    public void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(maintenancePanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    public void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(othersPanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
    }//GEN-LAST:event_otherButtonActionPerformed

    public void dashboardNewMaintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNewMaintenanceButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(maintenancePanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
    }//GEN-LAST:event_dashboardNewMaintenanceButtonActionPerformed

    public void actionPayStripeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPayStripeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionPayStripeButtonActionPerformed

    public void maintenanceRequestSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceRequestSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceRequestSearchTextFieldActionPerformed

    public void maintenanceRequestSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceRequestSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceRequestSubmitButtonActionPerformed

    public void accountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseClicked
        // TODO add your handling code here:
        tenantDashboard.removeAll();
        tenantDashboard.add(accountPanel);
        tenantDashboard.repaint();
        tenantDashboard.revalidate();
        System.out.println("Account clicked");
    }//GEN-LAST:event_accountLabelMouseClicked

    public void paymentHistoryListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentHistoryListTableMouseClicked
        System.out.println("table clicked");
        
    }//GEN-LAST:event_paymentHistoryListTableMouseClicked

    public void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
        // TODO add your handling code here:
        System.out.print("sign out");
    }//GEN-LAST:event_signoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel actionPayDisplayLabel;
    private javax.swing.JButton actionPayPaypalButton;
    private javax.swing.JButton actionPayStripeButton;
    private javax.swing.JButton actionPayVisaButton;
    private javax.swing.JLabel amountToPayDisplayLabel;
    private javax.swing.JLabel breakdownDamagesAmountLabel;
    private javax.swing.JLabel breakdownDamagesDisplayLabel;
    private javax.swing.JLabel breakdownLateAmountLabel;
    private javax.swing.JLabel breakdownLateDisplayLabel;
    private javax.swing.JLabel breakdownRentAmountLabel;
    private javax.swing.JLabel breakdownRentDisplayLabel;
    private javax.swing.JLabel breakdownTotalAmountDisplayLabel;
    private javax.swing.JLabel breakdownTotalAmountLabel;
    private javax.swing.JPanel costActionsPanel;
    private javax.swing.JPanel costBreakdownPanel;
    private javax.swing.JPanel costDetailsPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JScrollPane dashboardMaintenanceSummaryScrollPane;
    private javax.swing.JTable dashboardMaintenanceSummaryTable;
    private javax.swing.JButton dashboardNewMaintenanceButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel displayDateLabel;
    private javax.swing.JLabel displayRentLabel;
    private javax.swing.JLabel dobDisplayLabel;
    private javax.swing.JLabel dueDateDisplayLabel;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JLabel emailDisplayLabel;
    private javax.swing.JLabel firstnameDisplayLabel;
    private javax.swing.JLabel genderDisplayLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JButton homePaymentButton;
    private javax.swing.JScrollPane inspectionScrollPane;
    private javax.swing.JTable inspectionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastnameDisplayLabel;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JLabel maintenanceDescriptionLabel;
    private javax.swing.JScrollPane maintenanceDescriptionScrollPane;
    private javax.swing.JTextArea maintenanceDescriptionTextArea;
    private javax.swing.JPanel maintenanceDetailsPanel;
    private javax.swing.JPanel maintenancePanel;
    private javax.swing.JScrollPane maintenanceRequestListScrollPane;
    private javax.swing.JTable maintenanceRequestListTable;
    private javax.swing.JPanel maintenanceRequestPanel;
    private javax.swing.JButton maintenanceRequestSearchButton;
    private javax.swing.JTextField maintenanceRequestSearchTextField;
    private javax.swing.JButton maintenanceRequestSubmitButton;
    private javax.swing.JPanel maintenanceTrackingPanel;
    private javax.swing.JPanel menubarPanel;
    private javax.swing.JScrollPane menubarScrollPane;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JButton otherButton;
    private javax.swing.JPanel othersPanel;
    private javax.swing.JButton paymentButton;
    private javax.swing.JPanel paymentDetailPanel;
    private javax.swing.JScrollPane paymentHistoryListScrollPane;
    private javax.swing.JTable paymentHistoryListTable;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel phoneNumberDisplayLabel;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JButton signoutButton;
    private javax.swing.JLayeredPane tenantDashboard;
    private javax.swing.JTabbedPane tenantDashboard1;
    private javax.swing.JLabel tenantDobValueLabel;
    private javax.swing.JLabel tenantDobValueLabel1;
    private javax.swing.JLabel tenantEmailValueLabel;
    private javax.swing.JLabel tenantFirstnameValueLabel;
    private javax.swing.JPanel tenantFormPanel;
    private javax.swing.JLabel tenantGenderValueLabel1;
    private javax.swing.JLabel tenantLastnameValueLabel1;
    private javax.swing.JLabel tenantName;
    private javax.swing.JPanel tenantPanel;
    private javax.swing.JLabel tenantPhoneValueLabel;
    private javax.swing.JLabel tenantidDisplayLabel;
    private javax.swing.JLabel tenantidValueLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
    

    
    
}
