/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rentalsystem.View;

import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class TenantView extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TenantView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenantPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        menubarPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        otherButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        tenantDashboard = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        greetingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tenantName = new javax.swing.JLabel();
        paymentDetailPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        displayRentLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        displayDateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homePaymentButton = new javax.swing.JButton();
        receiptPanel = new javax.swing.JPanel();
        maintenanceTrackingPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dashboardMaintenanceSummaryTable = new javax.swing.JTable();
        dashboardNewMaintenanceButton = new javax.swing.JButton();
        notificationPanel = new javax.swing.JPanel();
        paymentPanel = new javax.swing.JPanel();
        costDetailsPanel = new javax.swing.JPanel();
        costBreakdownPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        costActionsPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        paymentHistoryListScrollPane = new javax.swing.JScrollPane();
        paymentHistoryListTable = new javax.swing.JTable();
        maintenancePanel = new javax.swing.JPanel();
        maintenanceRequestPanel = new javax.swing.JPanel();
        maintenanceRequestSearchTextField = new javax.swing.JTextField();
        maintenanceRequestSearchButton = new javax.swing.JButton();
        maintenanceRequestListScrollPane = new javax.swing.JScrollPane();
        maintenanceRequestListTable = new javax.swing.JTable();
        maintenanceDetailsPanel = new javax.swing.JPanel();
        maintenanceDescriptionLabel = new javax.swing.JLabel();
        maintenanceRequestScrollPane = new javax.swing.JScrollPane();
        maintenanceDescriptionTextArea = new javax.swing.JTextArea();
        maintenanceHouseDetailsButton = new javax.swing.JButton();
        othersPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        tenantPanel.setBackground(new java.awt.Color(255, 204, 204));

        titlePanel.setBackground(new java.awt.Color(255, 204, 204));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        titleLabel.setText("Company Name");

        accountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rentalsystem/images/account.png"))); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 995, Short.MAX_VALUE)
                .addComponent(accountLabel)
                .addGap(30, 30, 30))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(accountLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        menubarPanel.setBackground(new java.awt.Color(255, 204, 204));
        menubarPanel.setPreferredSize(new java.awt.Dimension(320, 100));

        dashboardButton.setBackground(new java.awt.Color(51, 51, 51));
        dashboardButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(204, 204, 204));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        dashboardButton.setFocusPainted(false);
        dashboardButton.setFocusable(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(200, 50));
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        paymentButton.setBackground(new java.awt.Color(51, 51, 51));
        paymentButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(204, 204, 204));
        paymentButton.setText("Payment");
        paymentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        paymentButton.setFocusPainted(false);
        paymentButton.setPreferredSize(new java.awt.Dimension(200, 50));
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        maintenanceButton.setBackground(new java.awt.Color(51, 51, 51));
        maintenanceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maintenanceButton.setForeground(new java.awt.Color(204, 204, 204));
        maintenanceButton.setText("Maintenance");
        maintenanceButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        maintenanceButton.setFocusPainted(false);
        maintenanceButton.setPreferredSize(new java.awt.Dimension(200, 50));
        maintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceButtonActionPerformed(evt);
            }
        });

        otherButton.setBackground(new java.awt.Color(51, 51, 51));
        otherButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        otherButton.setForeground(new java.awt.Color(204, 204, 204));
        otherButton.setText("Others");
        otherButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        otherButton.setFocusPainted(false);
        otherButton.setPreferredSize(new java.awt.Dimension(200, 50));
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });

        signoutButton.setBackground(new java.awt.Color(51, 51, 51));
        signoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(204, 204, 204));
        signoutButton.setText("Sign Out");
        signoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(153, 153, 153)));
        signoutButton.setFocusPainted(false);
        signoutButton.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout menubarPanelLayout = new javax.swing.GroupLayout(menubarPanel);
        menubarPanel.setLayout(menubarPanelLayout);
        menubarPanelLayout.setHorizontalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        menubarPanelLayout.setVerticalGroup(
            menubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(otherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tenantDashboard.setBackground(new java.awt.Color(255, 204, 204));
        tenantDashboard.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tenantDashboard.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tenantDashboard.setEnabled(false);
        tenantDashboard.setFocusable(false);
        tenantDashboard.setRequestFocusEnabled(false);
        tenantDashboard.setVerifyInputWhenFocusTarget(false);

        dashboardPanel.setBackground(new java.awt.Color(255, 204, 204));

        greetingPanel.setBackground(new java.awt.Color(255, 204, 204));
        greetingPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 153, 153)));
        greetingPanel.setPreferredSize(new java.awt.Dimension(286, 120));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        jLabel1.setText("Hi");

        tenantName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        tenantName.setText("Name");

        javax.swing.GroupLayout greetingPanelLayout = new javax.swing.GroupLayout(greetingPanel);
        greetingPanel.setLayout(greetingPanelLayout);
        greetingPanelLayout.setHorizontalGroup(
            greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greetingPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tenantName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        greetingPanelLayout.setVerticalGroup(
            greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greetingPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(greetingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tenantName))
                .addGap(30, 30, 30))
        );

        paymentDetailPanel.setPreferredSize(new java.awt.Dimension(400, 275));

        jPanel1.setBackground(new java.awt.Color(255, 227, 227));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Next Payment of");

        displayRentLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        displayRentLabel.setForeground(new java.awt.Color(255, 102, 102));
        displayRentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayRentLabel.setText("999");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("due in ");

        displayDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        displayDateLabel.setForeground(new java.awt.Color(255, 102, 102));
        displayDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayDateLabel.setText("DD-MM-YYYY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayRentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayRentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayDateLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        homePaymentButton.setBackground(new java.awt.Color(255, 227, 227));
        homePaymentButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homePaymentButton.setForeground(new java.awt.Color(255, 51, 51));
        homePaymentButton.setText("PAY NOW");
        homePaymentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        homePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePaymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentDetailPanelLayout = new javax.swing.GroupLayout(paymentDetailPanel);
        paymentDetailPanel.setLayout(paymentDetailPanelLayout);
        paymentDetailPanelLayout.setHorizontalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homePaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paymentDetailPanelLayout.setVerticalGroup(
            paymentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        receiptPanel.setPreferredSize(new java.awt.Dimension(400, 275));

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        maintenanceTrackingPanel.setBackground(new java.awt.Color(255, 204, 204));
        maintenanceTrackingPanel.setPreferredSize(new java.awt.Dimension(400, 600));

        dashboardMaintenanceSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "Recieved", "arun"}
            },
            new String [] {
                "Ticket no", "Status", "Requested by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dashboardMaintenanceSummaryTable);

        dashboardNewMaintenanceButton.setBackground(new java.awt.Color(255, 227, 227));
        dashboardNewMaintenanceButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboardNewMaintenanceButton.setForeground(new java.awt.Color(255, 51, 51));
        dashboardNewMaintenanceButton.setText("New Request");
        dashboardNewMaintenanceButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        dashboardNewMaintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNewMaintenanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maintenanceTrackingPanelLayout = new javax.swing.GroupLayout(maintenanceTrackingPanel);
        maintenanceTrackingPanel.setLayout(maintenanceTrackingPanelLayout);
        maintenanceTrackingPanelLayout.setHorizontalGroup(
            maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTrackingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(dashboardNewMaintenanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceTrackingPanelLayout.setVerticalGroup(
            maintenanceTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTrackingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardNewMaintenanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        notificationPanel.setPreferredSize(new java.awt.Dimension(0, 275));

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(paymentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maintenanceTrackingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maintenanceTrackingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(notificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );

        tenantDashboard.addTab("", dashboardPanel);

        paymentPanel.setBackground(new java.awt.Color(204, 255, 204));

        costBreakdownPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Amount to Pay");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Rent");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Damages");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Late Fee");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("99");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("99");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("99");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Total To pay");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("999");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Due on: ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("dd/mm/yyyy");

        javax.swing.GroupLayout costBreakdownPanelLayout = new javax.swing.GroupLayout(costBreakdownPanel);
        costBreakdownPanel.setLayout(costBreakdownPanelLayout);
        costBreakdownPanelLayout.setHorizontalGroup(
            costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, costBreakdownPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addGap(37, 37, 37)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, costBreakdownPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(30, 30, 30))
        );
        costBreakdownPanelLayout.setVerticalGroup(
            costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costBreakdownPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 51, Short.MAX_VALUE)
                .addGroup(costBreakdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40))
        );

        costActionsPanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Pay Here");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Stripe");
        jButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("PayPal");
        jButton2.setPreferredSize(new java.awt.Dimension(250, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Visa");
        jButton3.setPreferredSize(new java.awt.Dimension(250, 50));

        javax.swing.GroupLayout costActionsPanelLayout = new javax.swing.GroupLayout(costActionsPanel);
        costActionsPanel.setLayout(costActionsPanelLayout);
        costActionsPanelLayout.setHorizontalGroup(
            costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        costActionsPanelLayout.setVerticalGroup(
            costActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costActionsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout costDetailsPanelLayout = new javax.swing.GroupLayout(costDetailsPanel);
        costDetailsPanel.setLayout(costDetailsPanelLayout);
        costDetailsPanelLayout.setHorizontalGroup(
            costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costBreakdownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        costDetailsPanelLayout.setVerticalGroup(
            costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(costDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costBreakdownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        paymentHistoryListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Due Date", "Paid on", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        paymentHistoryListScrollPane.setViewportView(paymentHistoryListTable);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentHistoryListScrollPane))
                .addGap(0, 0, 0))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentHistoryListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        tenantDashboard.addTab("", paymentPanel);

        maintenanceRequestSearchTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        maintenanceRequestSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceRequestSearchTextFieldActionPerformed(evt);
            }
        });

        maintenanceRequestSearchButton.setBackground(new java.awt.Color(248, 255, 255));
        maintenanceRequestSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maintenanceRequestSearchButton.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Documents\\UoN-notes\\YEAR 2\\CSY2094 - JAVA\\1 AS2\\RentalSystem\\src\\main\\java\\com\\mycompany\\rentalsystem\\images\\magnifying-glass.png")); // NOI18N
        maintenanceRequestSearchButton.setBorder(null);

        maintenanceRequestListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        maintenanceRequestListScrollPane.setViewportView(maintenanceRequestListTable);

        javax.swing.GroupLayout maintenanceRequestPanelLayout = new javax.swing.GroupLayout(maintenanceRequestPanel);
        maintenanceRequestPanel.setLayout(maintenanceRequestPanelLayout);
        maintenanceRequestPanelLayout.setHorizontalGroup(
            maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                .addGroup(maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(maintenanceRequestSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(maintenanceRequestSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(maintenanceRequestPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(maintenanceRequestListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceRequestPanelLayout.setVerticalGroup(
            maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceRequestPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(maintenanceRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maintenanceRequestSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(maintenanceRequestSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintenanceRequestListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        maintenanceDescriptionLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        maintenanceDescriptionLabel.setText("Description");

        maintenanceDescriptionTextArea.setColumns(20);
        maintenanceDescriptionTextArea.setRows(5);
        maintenanceRequestScrollPane.setViewportView(maintenanceDescriptionTextArea);

        maintenanceHouseDetailsButton.setBackground(new java.awt.Color(248, 255, 255));
        maintenanceHouseDetailsButton.setText("Submit New Request");
        maintenanceHouseDetailsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        maintenanceHouseDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceHouseDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maintenanceDetailsPanelLayout = new javax.swing.GroupLayout(maintenanceDetailsPanel);
        maintenanceDetailsPanel.setLayout(maintenanceDetailsPanelLayout);
        maintenanceDetailsPanelLayout.setHorizontalGroup(
            maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceDetailsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceRequestScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceDescriptionLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maintenanceHouseDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceDetailsPanelLayout.setVerticalGroup(
            maintenanceDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maintenanceRequestScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(maintenanceHouseDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout maintenancePanelLayout = new javax.swing.GroupLayout(maintenancePanel);
        maintenancePanel.setLayout(maintenancePanelLayout);
        maintenancePanelLayout.setHorizontalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        maintenancePanelLayout.setVerticalGroup(
            maintenancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maintenanceDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tenantDashboard.addTab("", maintenancePanel);

        jLabel5.setText("view contract");

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othersPanelLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel5)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othersPanelLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel5)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        tenantDashboard.addTab("", othersPanel);

        javax.swing.GroupLayout tenantPanelLayout = new javax.swing.GroupLayout(tenantPanel);
        tenantPanel.setLayout(tenantPanelLayout);
        tenantPanelLayout.setHorizontalGroup(
            tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantPanelLayout.createSequentialGroup()
                .addGroup(tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tenantPanelLayout.createSequentialGroup()
                        .addComponent(menubarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenantDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(tenantPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tenantPanelLayout.setVerticalGroup(
            tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenantPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tenantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menubarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenantDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tenantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tenantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(0);

    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void homePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePaymentButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(1);
    }//GEN-LAST:event_homePaymentButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(1);
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(2);
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(3);
    }//GEN-LAST:event_otherButtonActionPerformed

    private void dashboardNewMaintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNewMaintenanceButtonActionPerformed
        // TODO add your handling code here:
        tenantDashboard.setSelectedIndex(2);
    }//GEN-LAST:event_dashboardNewMaintenanceButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maintenanceRequestSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceRequestSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceRequestSearchTextFieldActionPerformed

    private void maintenanceHouseDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceHouseDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceHouseDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JPanel costActionsPanel;
    private javax.swing.JPanel costBreakdownPanel;
    private javax.swing.JPanel costDetailsPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JTable dashboardMaintenanceSummaryTable;
    private javax.swing.JButton dashboardNewMaintenanceButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel displayDateLabel;
    private javax.swing.JLabel displayRentLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JButton homePaymentButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JLabel maintenanceDescriptionLabel;
    private javax.swing.JTextArea maintenanceDescriptionTextArea;
    private javax.swing.JPanel maintenanceDetailsPanel;
    private javax.swing.JButton maintenanceHouseDetailsButton;
    private javax.swing.JPanel maintenancePanel;
    private javax.swing.JScrollPane maintenanceRequestListScrollPane;
    private javax.swing.JTable maintenanceRequestListTable;
    private javax.swing.JPanel maintenanceRequestPanel;
    private javax.swing.JScrollPane maintenanceRequestScrollPane;
    private javax.swing.JButton maintenanceRequestSearchButton;
    private javax.swing.JTextField maintenanceRequestSearchTextField;
    private javax.swing.JPanel maintenanceTrackingPanel;
    private javax.swing.JPanel menubarPanel;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JButton otherButton;
    private javax.swing.JPanel othersPanel;
    private javax.swing.JButton paymentButton;
    private javax.swing.JPanel paymentDetailPanel;
    private javax.swing.JScrollPane paymentHistoryListScrollPane;
    private javax.swing.JTable paymentHistoryListTable;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JButton signoutButton;
    private javax.swing.JTabbedPane tenantDashboard;
    private javax.swing.JLabel tenantName;
    private javax.swing.JPanel tenantPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    public void setPage(String buttonPressed) {
        switch (buttonPressed) {
            case "Dashboard" -> tenantDashboard.setSelectedIndex(0);
            case "Payments" -> tenantDashboard.setSelectedIndex(1);
            case "Maintenance" -> tenantDashboard.setSelectedIndex(2);
            case "Contracts" -> tenantDashboard.setSelectedIndex(3);
            case "Others" -> tenantDashboard.setSelectedIndex(4);
            default -> tenantDashboard.setSelectedIndex(0);
        }
         
    }
    //add this code inside tenantDashboard settings to remove the border
    
    /*Insets insets = UIManager.getInsets("TabbedPane.contentBorderInsets");
insets.top = -1;
insets.bottom = -1;
insets.left = -1;
insets.right = -1;
UIManager.put("TabbedPane.contentBorderInsets", insets);
     */
}
